### PR TITLE
Theme Revamp

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
### Bug:
- The previous theme implementation had several bugs and issues that affected the overall user experience. These included incorrect theme rendering, hydration errors, and problems with component refresh when the theme changed on the client.

### Solution:
To address these issues, we have revamped the theme implementation and made the following changes:

### Changes
- Added the ``next-themes`` library to enhance theme functionality and provide a more robust solution.
- Fixed the theme state and ensured proper component refresh when the theme changed on the client.
- Resolved the issue related to loading the source files correctly.
- Fixed the debug panel and ``Navbar`` components, which were displaying an incorrect theme.
- Addressed the hydration errors that occurred during the rendering process.

closes https://github.com/EveripediaNetwork/issues/issues/1458

### CODE REVIEW

**Comment by Tolu-Mals** [comment]
It works fine, but there are now errors in the console.

**Comment by Tolu-Mals** [comment]
It works fine, but there are now errors in the console.

**Comment by Tolu-Mals** [comment]
It works fine, but there are now errors in the console.

**Comment by Adebesin-Cell** [comment]
> It works fine, but there are now errors in the console.

Ha, let me see. I'll work on them.

**Review by Tolu-Mals — APPROVED** [review]
Looks good, great job ✨

**Review by Royal-lobster — APPROVED** [review]

**Pull request merged**
