### PR TITLE
Updated changes for iq gpt

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
**Changes Made:**

- More rounded corners
- Paddings in the result card
- Disabled search bar when searching 
- Share Modal
- New action Icons
- Italic source text (for now until design ready)
- Linked Header  (The header is linked but it doesn't really do anything except its meant to reload the page when clicked)
- View on smaller screens

https://user-images.githubusercontent.com/75235148/229278120-89882ab6-25df-4c07-bd56-110a4df2bb28.mp4

closes: https://github.com/EveripediaNetwork/issues/issues/1170 , https://github.com/EveripediaNetwork/issues/issues/1162, https://github.com/EveripediaNetwork/issues/issues/1184

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
- This should be sitting in the middle on the mobile bp and also in md bp.
image

- This stroke that separates the footer is not meant to be this thick. (dark mode) use alpha white 400.
image

- the distance between these guys is too much
image

**Comment by Royal-lobster** [comment]
small bug i found - It goes to infinite loading in case of empty array from api

CleanShot 2023-04-03 at 19 42 01@2x
CleanShot 2023-04-03 at 19 42 12@2x
CleanShot 2023-04-03 at 19 42 17@2x

**Comment by Simplypheyie96** [comment]
Also, i think we should make the search bar a little longer. I'll inform wale to work on that.
image

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
The only obvious change is the addition of the new font for source.
other things are still the same. 
noticed that the search bar isn't in the middle even for the bigger bp too.

**Pull request merged**
