### PR TITLE
DebugOptions Revamp and Coinness kr integration

### PR DESCRIPTION
**Pull request by Royal-lobster**
# Changes
- changes the way we store scopes allowing more flexible additions for metadata
- implements filtering for language specific scopes
- adds coinness korea to ui
- redesigns all of debug options with use of radix ui elements 
- redesigned scope selection model and reordered it to top 
- simplify logic with persist middleware on zustand store instead of implementing from scratch.
- adds toasts on restore and save actions of debug options

# Screenshots
CleanShot 2023-06-29 at 11 23 27@2x
CleanShot 2023-06-29 at 11 24 12@2x

Fixes: https://github.com/EveripediaNetwork/issues/issues/1503
Fixes: https://github.com/EveripediaNetwork/issues/issues/1504
Fixes : https://github.com/EveripediaNetwork/issues/issues/1505
Fixes: https://github.com/EveripediaNetwork/issues/issues/1506

### CODE REVIEW

**Comment by Tolu-Mals** [comment]
I think the scope options would look better if the border color was a less saturated pink on light mode.

**Comment by Tolu-Mals** [comment]
I noticed that the open and close animations for the debug panel are gone

**Comment by Royal-lobster** [comment]
> I noticed that the open and close animations for the debug panel are gone

Ohh thats true, let me try to retrive it

**Comment by Royal-lobster** [comment]
@Tolu-Mals let's handle the animations again in another pr, because with radix ui there is something i am missing that it's unmounting the component instead of making it hidden. it needs some more investigation

**Comment by Tolu-Mals** [comment]
> @Tolu-Mals let's handle the animations again in another pr, because with radix ui there is something i am missing that it's unmounting the component instead of making it hidden. it needs some more investigation 

Oh alright.

**Review by Tolu-Mals — APPROVED** [review]

**Pull request merged**
