### PR TITLE
Add commit SHA

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
## Changes:

- Add version number to track git commits

### MEDIA
pika-1688042494350-1x

fixes https://github.com/EveripediaNetwork/issues/issues/1496

### CODE REVIEW

**Comment by Royal-lobster** [comment]
How is this instead ? so we can save some space on footer

CleanShot 2023-06-29 at 19 29 47@2x

**Review by Tolu-Mals — COMMENTED** [review]
The footer is a server component right? So that means we can get all this values directly inside the component, no need for creating a route.

**Comment by Royal-lobster** [comment]
> The footer is a server component right? So that means we can get all this values directly inside the component, no need for creating a route.

Oh yes thats right. let me see if i can make it work

**Comment by Royal-lobster** [comment]
cool looks like its working

**Pull request merged**
